default: &default
  encryption_key: <%= ENV.fetch('CANVAS_LMS_ENCRYPTION_KEY') %>
  jwt_encryption_keys: <%= ENV.fetch('CANVAS_LMS_JWT_ENCRYPTION_KEYS') %>

production: *default

development: *default

test: *default
